export const screens = {
    splash: document.getElementById('splash-screen'),
    lobby: document.getElementById('lobby-screen'),
    createRoom: document.getElementById('create-room-screen'),
    roomList: document.getElementById('room-list-screen'),
    joinerSetup: document.getElementById('joiner-setup-screen'),
    waiting: document.getElementById('waiting-room-screen'),
    game: document.getElementById('main-game-screen'),
    gameOver: document.getElementById('game-over-screen')
};

export const ui = {
    splashScreen: screens.splash,
    goToCreateBtn: document.getElementById('go-to-create-btn'),
    goToJoinBtn: document.getElementById('go-to-join-btn'),
    hostNameInput: document.getElementById('host-name-input'),
    newRoomNameInput: document.getElementById('new-room-name-input'),
    newRoomPasswordInput: document.getElementById('new-room-password-input'),
    modeOptionBtns: document.querySelectorAll('.mode-option-btn'),
    confirmCreateBtn: document.getElementById('confirm-create-btn'),
    roomListContent: document.getElementById('room-list-content'),
    joinerRoomNameDisplay: document.getElementById('joiner-room-name-display'),
    joinerNameInput: document.getElementById('joiner-name-input'),
    confirmJoinBtn: document.getElementById('confirm-join-btn'),
    roomCodeText: document.getElementById('room-code-text'),
    playerSlots: {
        player1: document.getElementById('player1-slot'),
        player2: document.getElementById('player2-slot'),
        player3: document.getElementById('player3-slot'),
        player4: document.getElementById('player4-slot')
    },
    waitingMessage: document.getElementById('waiting-message'),
    startGameBtn: document.getElementById('start-game-btn'),
    turnIndicator: document.getElementById('turn-indicator'),
    turnText: document.getElementById('turn-text'),
    turnTimerDisplay: document.getElementById('turn-timer-display'),
    ourNumberDisplay: document.getElementById('our-number-display'),
    historyLog: document.getElementById('history-log'),
    historyTargetName: document.getElementById('history-target-name'),
    guessNumberContainer: document.getElementById('guess-number-container'),
    numberPadContainer: document.getElementById('number-pad-container'),
    chanceDots: [document.getElementById('chance-1'), document.getElementById('chance-2'), document.getElementById('chance-3')],
    submitFinalAnswerBtn: document.getElementById('submit-final-answer-btn'),
    spectatorOverlay: document.getElementById('spectator-overlay'),
    spectatorMessage: document.getElementById('spectator-message'),
    gameOverTitle: document.getElementById('game-over-title'),
    winnerName: document.getElementById('winner-name'),
    gameOverMessage: document.getElementById('game-over-message'),
    gameOverNumbersContainer: document.getElementById('game-over-numbers-container'),
    rematchBtn: document.getElementById('rematch-btn'),
    backToLobbyBtn: document.getElementById('back-to-lobby-btn'),
    passwordModal: document.getElementById('password-modal'),
    passwordModalRoomName: document.getElementById('password-modal-room-name'),
    passwordModalInput: document.getElementById('password-modal-input'),
    passwordModalSubmitBtn: document.getElementById('password-modal-submit-btn'),
    toast: document.getElementById('toast'),
    actionToast: document.getElementById('action-toast'),
    actionToastText: document.getElementById('action-toast-text'),
    soundControl: document.getElementById('sound-control'),
    soundIcon: document.getElementById('sound-icon'),
    scoreboardContent: document.getElementById('scoreboard-content'),
    cardDisplaySection: document.getElementById('card-display-section'),
    cardContent: document.getElementById('card-content'),
    guessControls: document.querySelector('.guess-controls'),
    finalAnswerSection: document.querySelector('.final-answer-section'),
};
